PLAYER_DEFAULT_HEALTH: 100.0
PLAYER_DEFAULT_HEALTH_CAP: 200.0
PLAYER_DEFAULT_HEALTH_CAP_MODIFIER: 1.0
PLAYER_DEFAULT_HEALTH_MODIFIER: 1.0
PLAYER_DEFAULT_ATTACK: 1.0
PLAYER_DEFAULT_DEFENSE: 1.0
PLAYER_DEFAULT_EXPERIENCE: 0.0
PLAYER_LEVEL_INCREASE: 1
NUM_ENEMIES: 10
NUM_MOVES: 4
MAP_SIZE: 14
DEFAULT_MODIFIER: 1.0