PLAYER_DEFAULT_HEALTH: 100.0
PLAYER_DEFAULT_HEALTH_CAP: 200.0
PLAYER_DEFAULT_HEALTH_CAP_MODIFIER: 1.0
PLAYER_DEFAULT_HEALTH_MODIFIER: 1.0
PLAYER_DEFAULT_ATTACK_MODIFIER: 1.0
PLAYER_DEFAULT_DEFENSE_MODIFIER: 1.0
PLAYER_EXPERIENCE_CAP: 10.0
PLAYER_DEFAULT_EXPERIENCE: 0.0
PLAYER_DEFAULT_LEVEL: 0
PLAYER_LEVEL_INCREASE: 1
NUM_ENEMIES: 10
NUM_PLAYER_MOVES: 4
MAP_SIZE: 20
DEFAULT_MODIFIER: 1.0
MOVES_LEARNING_INTERVAL: 5
EXPERIENCE_MULTIPLIER: 0.2
