PLAYER_STARTING_POSITION_Y: 10
PLAYER_STARTING_POSITION_X: 10
PLAYER_DEFAULT_HEALTH: 100.0
PLAYER_DEFAULT_HEALTH_CAP: 200.0
PLAYER_DEFAULT_ATTACK: 1.0
PLAYER_DEFAULT_DEFENSE: 1.0
PLAYER_DEFAULT_EXPERIENCE: 0.0
PLAYER_LEVEL_INCREASE: 1
STARTING_PLAYER_ANIMATION: boy_up_1.png
NUM_ENEMIES: 20
MAP_SIZE: 20